import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./context/AppProvider";
import { Header } from "./components/Header";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang="en">
        <body>
          <Suspense fallback={<div>Loading...</div>}>
            <Header />
          </Suspense>
          <main>{children}</main>
        </body>
      </html>
    </AppProvider>
  );
}
