name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 10 * * 1,5" # Twice a week
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase alive
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/keepalive" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"note": "Ping on '"$(date -u)"'"}'
